apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: min-leesah-quizapp
  namespace: leesah-quiz
  labels:
    team: leesah-quiz
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://min-leesah-quizapp.dev.intern.nav.no
  liveness:
    path: /alive
    timeout: 1
  readiness:
    initialDelay: 20
    path: /ready
    timeout: 1
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  secureLogs:
    enabled: true
  env:
    - name: DEVELOPMENT
      value: "false"
