apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: min-leesah-quizapp
  namespace: leesah-quiz
  labels:
    team: leesah-quiz
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://min-leesah-quizapp.dev.intern.nav.no
  liveness:
    path: isalive
  readiness:
    initialDelay: 60
    path: isready
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  kafka:
    pool: nav-dev
  env:
    - name: QUIZ_TOPIC
      value: "leesah-quiz.leesah-rapid-v1"
